name: Deploy CakePHP Review Environment

# このWorkflowはPull Requestイベントで動作する
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
env:
  DEPLOY_NAME: "${{ github.event.repository.name }}-pr${{ github.event.pull_request.number }}"
  DEPLOY_DIR: "/var/www/html/${{ github.event.repository.name }}-pr${{ github.event.pull_request.number }}"
  REVIEW_URL: "https://${{ secrets.SITE_DOMAIN }}/${{ github.event.repository.name }}-pr${{ github.event.pull_request.number }}"

jobs:
  # PR作成・更新時にレビュー環境をデプロイ
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Deploy Review Environment

    steps:
      # サーバー上でレビュー環境をセットアップ
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_SERVER_HOST }}
          username: ${{ secrets.REVIEW_SERVER_USER }}
          key: ${{ secrets.REVIEW_SERVER_SSH_KEY }}
          script: |
            if [ ! -d "${{ env.DEPLOY_DIR }}/.git" ]; then
              echo "Review directory not found. Cloning repository..."
              sudo mkdir -p "${{ env.DEPLOY_DIR }}"
              sudo chown -R $USER:$USER "${{ env.DEPLOY_DIR }}"
              git clone --branch ${{ github.head_ref }} git@github.com:${{ github.repository }} "${{ env.DEPLOY_DIR }}"
            else
              echo "Review directory exists. Fetching latest changes..."
              cd "${{ env.DEPLOY_DIR }}"
              git fetch origin
              git reset --hard origin/${{ github.head_ref }}
            fi

            cd "${{ env.DEPLOY_DIR }}"

            # .htaccessファイルを書き換え
            cat > .htaccess <<'EOF'
            <IfModule mod_rewrite.c>
            RewriteEngine on
            RewriteBase    /
            RewriteRule    ^(\.well-known/.*)$ $1 [L]
            RewriteRule    ^$    ${{ env.DEPLOY_NAME }}/webroot/    [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule ^ ${{ env.DEPLOY_NAME }}/webroot/index.php [L]
            </IfModule>
            EOF

            # Composerで依存パッケージをインストール
            composer install

            # プラグイン内のアセットをコピー
            bin/cake plugin assets copy

            # データベースマイグレーションを実行
            bin/cake migrations migrate

            # キャッシュをクリア
            bin/cake cache clear_all

      # レビューURLを表示
      - name: Output Review URL
        run: |
          echo "Review environment is available: ${{ env.REVIEW_URL }}"

  # PRが閉じられたとき、レビュー環境を削除
  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Delete Review Environment

    steps:
      # サーバー上のレビュー環境をSSH接続して削除
      - name: Delete review environment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_SERVER_HOST }}
          username: ${{ secrets.REVIEW_SERVER_USER }}
          key: ${{ secrets.REVIEW_SERVER_SSH_KEY }}
          script: |
            if [ -d "${{ env.DEPLOY_DIR }}" ]; then
              echo "Deleting review environment: ${{ env.DEPLOY_DIR }}"
              sudo rm -rf "${{ env.DEPLOY_DIR }}"
            else
              echo "No review environment found for PR#${{ github.event.pull_request.number }}"
            fi
